server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
#      timeout: 1d
spring:
  profiles:
    active: dev
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peer-match?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 1
    redisson-database: 2
  session:
    timeout: 86400
    store-type: redis
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 数据库逻辑删除字段
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
executor:
  core-pool-size: 16
  max-pool-size: 32
  keep-alive-time: 5
  queue-capacity: 1000

canal:
  host: localhost
  port: 11111
  destination: example1
  user: canal
  password: canal

